# actually finds our LibreSSL static libs...

if (MSVC)
	set(__BUILD_TYPE_PREFIX "${CMAKE_BUILD_TYPE}/")
else()
	set(__BUILD_TYPE_PREFIX "")
endif()

set(OPENSSL_FOUND TRUE)
set(OPENSSL_INCLUDE_DIR "@MY_LIBRESSL_INCLUDE_DIR@")
set(OPENSSL_CRYPTO_LIBRARY "@MY_LIBRESSL_BUILD_DIR@/crypto/${__BUILD_TYPE_PREFIX}${CMAKE_STATIC_LIBRARY_PREFIX}crypto${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(OPENSSL_SSL_LIBRARY "@MY_LIBRESSL_BUILD_DIR@/ssl/${__BUILD_TYPE_PREFIX}${CMAKE_STATIC_LIBRARY_PREFIX}ssl${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(LIBRESSL_TLS_LIBRARY "@MY_LIBRESSL_BUILD_DIR@/tls/${__BUILD_TYPE_PREFIX}${CMAKE_STATIC_LIBRARY_PREFIX}tls${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(OPENSSL_LIBRARIES ${OPENSSL_CRYPTO_LIBRARY} ${OPENSSL_SSL_LIBRARY})

add_library(OpenSSL::Crypto UNKNOWN IMPORTED)
set_target_properties(OpenSSL::Crypto PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
)
set_target_properties(OpenSSL::Crypto PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C"
	IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
)

add_library(OpenSSL::SSL UNKNOWN IMPORTED)
set_target_properties(OpenSSL::SSL PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
)
set_target_properties(OpenSSL::SSL PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C"
	IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
)
set_target_properties(OpenSSL::SSL PROPERTIES
	INTERFACE_LINK_LIBRARIES OpenSSL::Crypto
)
